name: "Meow! Coverage"
description: "Code Coverage Action (with meows)"
branding:
  icon: "heart"
  color: "gray-dark"
inputs:
  source-prefix:
    description: "Prefix for locating source files in Lcov paths (for example 'src/')"
    required: true
  pr-number:
    description: "Pull Request Identifier, mandatory if pr-based"
    required: false
  repo-name:
    description: "Repository Name"
    required: true
  commit-id:
    description: "Commit ID"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
  new-lcov-file:
    description: "New Lcov file path"
    required: true
  old-lcov-file:
    description: "Previous Lcov file path"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    MEOWCOV_SOURCE_PREFIX: ${{ inputs.source-prefix }}
    MEOWCOV_REPO_NAME: ${{ inputs.repo-name }}
    MEOWCOV_COMMIT_ID: ${{ inputs.commit-id }}
    MEOWCOV_GITHUB_TOKEN: ${{ inputs.github-token }}
    MEOWCOV_NEW_LCOV: ${{ inputs.new-lcov-file }}
    MEOWCOV_OLD_LCOV: ${{ inputs.old-lcov-file }}
    MEOWCOV_PR_NUMBER: ${{ inputs.pr-number }}
